# SHELL := /bin/bash
# PATH := /usr/local/bin:

all:
	pio -f -c vim run

flash:
	pio -f -c vim run --target upload

clean:
	pio -f -c vim run --target clean

program:
	pio -f -c vim run --target program

uploadfs:
	pio -f -c vim run --target uploadfs

update:
	pio -f -c vim update

compiledb:
	pio run -t compiledb

